FROM arm64v8/ubuntu:18.04

ENV CONFIG_PATH=/local \
ROOT_CONFIG_PATH=/local \
DEST_CONFIG_PATH=/app_launcher \
MOUNT_CONFIG_PATH=/local

COPY Build/launcher_binaries.tar.gz /launcher_binaries.tar.gz

RUN apt-get update && \
dpkg --remove docker docker-engine docker.io && \
apt-get install -y dos2unix apt-transport-https ca-certificates curl software-properties-common && \
mkdir /temp && \
mkdir /app && \
mkdir /app_launcher && \
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
apt-get update && \
apt-get install -y docker-ce

ADD Launcher/run.sh /app/run.sh

WORKDIR /
RUN tar -xvzf /launcher_binaries.tar.gz && \
rm /launcher_binaries.tar.gz && \
rm -rf /app/x64 && \
mv /app/arm64/* /app && \
rm -rf /app/arm64

RUN dos2unix /app/run.sh && \
chmod +x /app/run.sh && \
chmod +x /app/Launcher

EXPOSE 5000

#Run the app
ENTRYPOINT [ "/app/run.sh" ]